## NumPy 실습

In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2,3,4,5])

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [4]:
a[2]

2

In [5]:
a[-1]

5

In [6]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

## Tensor 실습
데이터로부터 직접 생성하기

In [9]:
import torch
import numpy as np

In [ ]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [ ]:
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
torch.ones(3,3) # 3x3 일 행렬

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(2) # 2행 영 벡터

tensor([0., 0.])

In [ ]:
torch.rand(5,6) # 5x6 랜덤 행렬

tensor([[5.0298e-01, 3.3023e-01, 1.1666e-01, 3.4544e-01, 8.3158e-01, 8.9340e-01],
        [7.1719e-01, 8.5634e-01, 1.7697e-01, 3.0523e-01, 9.2882e-04, 4.0220e-01],
        [2.9776e-01, 8.8183e-02, 5.1754e-02, 1.3377e-01, 4.0533e-01, 8.3218e-01],
        [4.1672e-01, 4.2948e-01, 3.1184e-01, 8.8037e-01, 6.3272e-01, 2.6423e-01],
        [8.0896e-01, 2.8470e-01, 9.8636e-01, 4.6373e-02, 1.4048e-02, 1.8264e-01]])

## NumPy 배열로부터 생성하기
Numpy 배열 -> tensor로 변환

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
np_array

array([[1, 2],
       [3, 4]])

In [ ]:
x_np

tensor([[1, 2],
        [3, 4]])

## 텐서의 속성
텐서의 모양(shape), 자료형(datatype), 어느 장치에 저장되는지 확인

In [ ]:
print(f"Shape of tensor: {x_data.shape}")
print(f"Datatype of tensor: {x_data.dtype}")
print(f"Device tensor is stored on: {x_data.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


In [10]:
# 빈 텐서 생성
x = torch.empty(5,4) # 5x4 행렬 생성
print(x) # 초기화되지 않은 행렬인 경우 해당 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타남

tensor([[5.9800e-35, 0.0000e+00, 7.0065e-44, 7.0065e-44],
        [6.3058e-44, 6.7262e-44, 7.7071e-44, 6.3058e-44],
        [7.0065e-44, 7.8473e-44, 1.1771e-43, 6.7262e-44],
        [7.1466e-44, 8.1275e-44, 6.8664e-44, 7.2868e-44],
        [8.1275e-44, 6.8664e-44, 7.2868e-44, 6.4460e-44]])


## 텐서의 크기와 타입 확인하기

In [11]:
x.size()

torch.Size([5, 4])

In [12]:
x.size()[1] # .size()는 텐서의 크기를 확인할 수 있으며 매우 자주 사용된다.

4

In [15]:
x = x.view(-1,10)

In [16]:
x.size()

torch.Size([2, 10])

In [ ]:
type(x) # type은 Python에서 사용되는 모든 것들을 종류를 보여줌

torch.Tensor