In [ ]:
import numpy as np

In [ ]:
a = np.array([0,1,2,3,4])

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a[2]

2

In [ ]:
a[-1]

4

In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [ ]:
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
np_array

array([[1, 2],
       [3, 4]])

In [ ]:
x_np

tensor([[1, 2],
        [3, 4]])

## 텐서의 속성
텐서의 모양(shape), 자료형(datatype), 어느 장치에 저장되는지 확인

In [ ]:
print(f"Shape of tensor: {x_data.shape}")
print(f"Datatype of tensor: {x_data.dtype}")
print(f"Device tensor is stored on: {x_data.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu
